server:
  port: 8082
spring:
  application:
    name: lagou-spider
  data:
    mongodb:
      database: lagou_spider
      host: 192.168.3.200
      port: 27017

gaode:
  # 高德app-key
  app-key: your-key
  # 自己家的经纬度，通过高德地图查，最多六位小数
  coordirate: 116.487506,39.818880
  # 所在城市
  city: 北京
  # 需求岗位
  kd: java