server:
  port: 8082
spring:
  application:
    name: spider-spider
  data:
    mongodb:
      database: lagou_spider
      host: 192.168.3.200
      port: 27017

gaode:
  # 高德app-key
  app-key: 2ffcebd1de4b5f2d4a3072313ef8e3de
  # 自己家的经纬度，通过高德地图查，最多六位小数
  coordirate: 116.407506,39.813480
  # 所在城市
  city: 北京
  # 需求岗位
  kd: java